m3d_model_destroy(pose0)
m3d_model_destroy(pose1)
d3d_model_clear(pose2)
d3d_model_destroy(pose2)
m3d_model_destroy(test[0])
m3d_model_destroy(test[1])
m3d_model_destroy(test[2])
m3d_model_destroy(test[3])
m3d_model_destroy(test[4])
m3d_model_destroy(test[5])

m3d_model_destroy(patk)
m3d_model_destroy(patk1)
m3d_model_destroy(patk2)
d3d_model_clear(patk3)
d3d_model_destroy(patk3)
